version: '3'
# DATABASE - POSTGRESQL
services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - "${POSTGRESQL_LOCALHOST_PORT}:${POSTGRESQL_DEFAULT_PORT}"
    env_file:
      - .env      

  # Nodejs Server - PM2
  api:
    build: .
    container_name: api-solid
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - api-solid-pg
    env_file:
      - .env 
    environment:
      - DOCKER=true
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pm2-runtime", "start", "ecosystem.config.js", "--env", "production"]
